# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: car_state.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'car_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61r_state.proto\x12\x06hannah\"K\n\x10\x43\x61rStateResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12$\n\x05state\x18\x02 \x01(\x0b\x32\x15.hannah.CarStateProto\"@\n\x17GetAllCarStatesResponse\x12%\n\x06states\x18\x01 \x03(\x0b\x32\x15.hannah.CarStateProto\"\x81\x04\n\rCarStateProto\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x11\n\tis_moving\x18\x04 \x01(\x08\x12\x15\n\rposition_date\x18\x05 \x01(\x03\x12\x10\n\x08odometer\x18\x06 \x01(\x05\x12\x13\n\x0btotal_range\x18\x07 \x01(\x05\x12\x15\n\ris_car_locked\x18\x08 \x01(\x08\x12\x18\n\x10\x64oor_lock_status\x18\t \x01(\t\x12\x16\n\x0eoverall_status\x18\n \x01(\t\x12/\n\x05\x64oors\x18\x0b \x03(\x0b\x32 .hannah.CarStateProto.DoorsEntry\x12\x33\n\x07windows\x18\x0c \x03(\x0b\x32\".hannah.CarStateProto.WindowsEntry\x12\x14\n\x0cowner_roomie\x18\r \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x0e \x01(\t\x12\r\n\x05plate\x18\x0f \x01(\t\x12\x0b\n\x03vin\x18\x10 \x01(\t\x12\x14\n\x0chome_address\x18\x11 \x01(\t\x1a,\n\nDoorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x1a.\n\x0cWindowsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x42=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'car_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannah'
  _globals['_CARSTATEPROTO_DOORSENTRY']._loaded_options = None
  _globals['_CARSTATEPROTO_DOORSENTRY']._serialized_options = b'8\001'
  _globals['_CARSTATEPROTO_WINDOWSENTRY']._loaded_options = None
  _globals['_CARSTATEPROTO_WINDOWSENTRY']._serialized_options = b'8\001'
  _globals['_CARSTATERESPONSE']._serialized_start=27
  _globals['_CARSTATERESPONSE']._serialized_end=102
  _globals['_GETALLCARSTATESRESPONSE']._serialized_start=104
  _globals['_GETALLCARSTATESRESPONSE']._serialized_end=168
  _globals['_CARSTATEPROTO']._serialized_start=171
  _globals['_CARSTATEPROTO']._serialized_end=684
  _globals['_CARSTATEPROTO_DOORSENTRY']._serialized_start=592
  _globals['_CARSTATEPROTO_DOORSENTRY']._serialized_end=636
  _globals['_CARSTATEPROTO_WINDOWSENTRY']._serialized_start=638
  _globals['_CARSTATEPROTO_WINDOWSENTRY']._serialized_end=684
# @@protoc_insertion_point(module_scope)
