# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event_stream.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'event_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import car_state_pb2 as car__state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65vent_stream.proto\x12\x06hannah\x1a\x0f\x63\x61r_state.proto\"\"\n\x0b\x45ventFilter\x12\x13\n\x0b\x65vent_types\x18\x01 \x03(\t\"\x97\x02\n\x0bHannahEvent\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12*\n\tcar_state\x18\n \x01(\x0b\x32\x15.hannah.CarStateProtoH\x00\x12\x34\n\x0eresident_event\x18\x0b \x01(\x0b\x32\x1a.hannah.ResidentEventProtoH\x00\x12>\n\x13system_notification\x18\x0c \x01(\x0b\x32\x1f.hannah.SystemNotificationEventH\x00\x12\x34\n\x0e\x66irmware_event\x18\r \x01(\x0b\x32\x1a.hannah.FirmwareEventProtoH\x00\x42\t\n\x07payload\"\'\n\x17SystemNotificationEvent\x12\x0c\n\x04text\x18\x01 \x01(\t\"5\n\x12\x46irmwareEventProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\".\n\x1cTriggerFirmwareUpdateRequest\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\"L\n\x12ResidentEventProto\x12\x11\n\troomie_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\r\n\x05\x65vent\x18\x03 \x01(\tB=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannah'
  _globals['_EVENTFILTER']._serialized_start=47
  _globals['_EVENTFILTER']._serialized_end=81
  _globals['_HANNAHEVENT']._serialized_start=84
  _globals['_HANNAHEVENT']._serialized_end=363
  _globals['_SYSTEMNOTIFICATIONEVENT']._serialized_start=365
  _globals['_SYSTEMNOTIFICATIONEVENT']._serialized_end=404
  _globals['_FIRMWAREEVENTPROTO']._serialized_start=406
  _globals['_FIRMWAREEVENTPROTO']._serialized_end=459
  _globals['_TRIGGERFIRMWAREUPDATEREQUEST']._serialized_start=461
  _globals['_TRIGGERFIRMWAREUPDATEREQUEST']._serialized_end=507
  _globals['_RESIDENTEVENTPROTO']._serialized_start=509
  _globals['_RESIDENTEVENTPROTO']._serialized_end=585
# @@protoc_insertion_point(module_scope)
