# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hannah_pb2 as hannah__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hannah_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HannahServiceStub:
    """============================================================
    Hannah gRPC Service

    Allows external services (Telegram bot, web UI, etc.) to:
    - query and manage the user registry
    - submit text commands and receive answers
    - trigger TTS announcements on satellites
    - inspect registered satellites
    - query live car state
    - subscribe to a stream of Hannah events (car parked, resident arrived, …)
    - register as a satellite audio proxy (Go gRPC proxy replaces UDP server)
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsers = channel.unary_unary(
                '/hannah.HannahService/GetUsers',
                request_serializer=hannah__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=hannah__pb2.GetUsersResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/hannah.HannahService/GetUser',
                request_serializer=hannah__pb2.GetUserRequest.SerializeToString,
                response_deserializer=hannah__pb2.UserResponse.FromString,
                _registered_method=True)
        self.LinkAccount = channel.unary_unary(
                '/hannah.HannahService/LinkAccount',
                request_serializer=hannah__pb2.LinkAccountRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UnlinkAccount = channel.unary_unary(
                '/hannah.HannahService/UnlinkAccount',
                request_serializer=hannah__pb2.UnlinkAccountRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SetTrustLevel = channel.unary_unary(
                '/hannah.HannahService/SetTrustLevel',
                request_serializer=hannah__pb2.SetTrustLevelRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SetSystemMessages = channel.unary_unary(
                '/hannah.HannahService/SetSystemMessages',
                request_serializer=hannah__pb2.SetSystemMessagesRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/hannah.HannahService/Login',
                request_serializer=hannah__pb2.LoginRequest.SerializeToString,
                response_deserializer=hannah__pb2.UserResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/hannah.HannahService/CreateUser',
                request_serializer=hannah__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=hannah__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/hannah.HannahService/UpdateUser',
                request_serializer=hannah__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/hannah.HannahService/DeleteUser',
                request_serializer=hannah__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetResidents = channel.unary_unary(
                '/hannah.HannahService/GetResidents',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.GetResidentsResponse.FromString,
                _registered_method=True)
        self.GetDevices = channel.unary_unary(
                '/hannah.HannahService/GetDevices',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.GetDevicesResponse.FromString,
                _registered_method=True)
        self.ControlDevice = channel.unary_unary(
                '/hannah.HannahService/ControlDevice',
                request_serializer=hannah__pb2.ControlDeviceRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SubmitText = channel.unary_unary(
                '/hannah.HannahService/SubmitText',
                request_serializer=hannah__pb2.SubmitTextRequest.SerializeToString,
                response_deserializer=hannah__pb2.SubmitTextResponse.FromString,
                _registered_method=True)
        self.SubmitVoice = channel.unary_unary(
                '/hannah.HannahService/SubmitVoice',
                request_serializer=hannah__pb2.SubmitVoiceRequest.SerializeToString,
                response_deserializer=hannah__pb2.SubmitVoiceResponse.FromString,
                _registered_method=True)
        self.Announce = channel.unary_unary(
                '/hannah.HannahService/Announce',
                request_serializer=hannah__pb2.AnnounceRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Notify = channel.unary_unary(
                '/hannah.HannahService/Notify',
                request_serializer=hannah__pb2.AgentNotification.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetSatellites = channel.unary_unary(
                '/hannah.HannahService/GetSatellites',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.GetSatellitesResponse.FromString,
                _registered_method=True)
        self.SetSatelliteRoom = channel.unary_unary(
                '/hannah.HannahService/SetSatelliteRoom',
                request_serializer=hannah__pb2.SetSatelliteRoomRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SetSatelliteDisplayName = channel.unary_unary(
                '/hannah.HannahService/SetSatelliteDisplayName',
                request_serializer=hannah__pb2.SetSatelliteDisplayNameRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SetSatelliteOwner = channel.unary_unary(
                '/hannah.HannahService/SetSatelliteOwner',
                request_serializer=hannah__pb2.SetSatelliteOwnerRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetRooms = channel.unary_unary(
                '/hannah.HannahService/GetRooms',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.GetRoomsResponse.FromString,
                _registered_method=True)
        self.GetGroups = channel.unary_unary(
                '/hannah.HannahService/GetGroups',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.GetGroupsResponse.FromString,
                _registered_method=True)
        self.CreateGroup = channel.unary_unary(
                '/hannah.HannahService/CreateGroup',
                request_serializer=hannah__pb2.CreateGroupRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateGroup = channel.unary_unary(
                '/hannah.HannahService/UpdateGroup',
                request_serializer=hannah__pb2.UpdateGroupRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DeleteGroup = channel.unary_unary(
                '/hannah.HannahService/DeleteGroup',
                request_serializer=hannah__pb2.DeleteGroupRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SetGroupRooms = channel.unary_unary(
                '/hannah.HannahService/SetGroupRooms',
                request_serializer=hannah__pb2.SetGroupRoomsRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetRoutines = channel.unary_unary(
                '/hannah.HannahService/GetRoutines',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.GetRoutinesResponse.FromString,
                _registered_method=True)
        self.CreateRoutine = channel.unary_unary(
                '/hannah.HannahService/CreateRoutine',
                request_serializer=hannah__pb2.CreateRoutineRequest.SerializeToString,
                response_deserializer=hannah__pb2.CreateRoutineResponse.FromString,
                _registered_method=True)
        self.UpdateRoutine = channel.unary_unary(
                '/hannah.HannahService/UpdateRoutine',
                request_serializer=hannah__pb2.UpdateRoutineRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DeleteRoutine = channel.unary_unary(
                '/hannah.HannahService/DeleteRoutine',
                request_serializer=hannah__pb2.DeleteRoutineRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetTriggers = channel.unary_unary(
                '/hannah.HannahService/GetTriggers',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.GetTriggersResponse.FromString,
                _registered_method=True)
        self.CreateTrigger = channel.unary_unary(
                '/hannah.HannahService/CreateTrigger',
                request_serializer=hannah__pb2.CreateTriggerRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateTrigger = channel.unary_unary(
                '/hannah.HannahService/UpdateTrigger',
                request_serializer=hannah__pb2.UpdateTriggerRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DeleteTrigger = channel.unary_unary(
                '/hannah.HannahService/DeleteTrigger',
                request_serializer=hannah__pb2.DeleteTriggerRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetSettings = channel.unary_unary(
                '/hannah.HannahService/GetSettings',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.GetSettingsResponse.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/hannah.HannahService/UpdateConfig',
                request_serializer=hannah__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CreateSetting = channel.unary_unary(
                '/hannah.HannahService/CreateSetting',
                request_serializer=hannah__pb2.CreateSettingRequest.SerializeToString,
                response_deserializer=hannah__pb2.CreateSettingResponse.FromString,
                _registered_method=True)
        self.DeleteSetting = channel.unary_unary(
                '/hannah.HannahService/DeleteSetting',
                request_serializer=hannah__pb2.DeleteSettingRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetCarState = channel.unary_unary(
                '/hannah.HannahService/GetCarState',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.CarStateResponse.FromString,
                _registered_method=True)
        self.GetAllCarStates = channel.unary_unary(
                '/hannah.HannahService/GetAllCarStates',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.GetAllCarStatesResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/hannah.HannahService/SubscribeEvents',
                request_serializer=hannah__pb2.EventFilter.SerializeToString,
                response_deserializer=hannah__pb2.HannahEvent.FromString,
                _registered_method=True)
        self.TriggerFirmwareUpdate = channel.unary_unary(
                '/hannah.HannahService/TriggerFirmwareUpdate',
                request_serializer=hannah__pb2.TriggerFirmwareUpdateRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RequestSatelliteCapture = channel.unary_unary(
                '/hannah.HannahService/RequestSatelliteCapture',
                request_serializer=hannah__pb2.SatelliteCaptureRequest.SerializeToString,
                response_deserializer=hannah__pb2.SatelliteCaptureResponse.FromString,
                _registered_method=True)
        self.ReleaseSatelliteCapture = channel.unary_unary(
                '/hannah.HannahService/ReleaseSatelliteCapture',
                request_serializer=hannah__pb2.SatelliteCaptureRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StreamSatelliteAudio = channel.unary_stream(
                '/hannah.HannahService/StreamSatelliteAudio',
                request_serializer=hannah__pb2.SatelliteCaptureRequest.SerializeToString,
                response_deserializer=hannah__pb2.SatelliteAudioChunk.FromString,
                _registered_method=True)
        self.TriggerPlink = channel.unary_unary(
                '/hannah.HannahService/TriggerPlink',
                request_serializer=hannah__pb2.TriggerPlinkRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RegisterProxy = channel.stream_stream(
                '/hannah.HannahService/RegisterProxy',
                request_serializer=hannah__pb2.ProxyHeartbeat.SerializeToString,
                response_deserializer=hannah__pb2.ProxyCommand.FromString,
                _registered_method=True)
        self.SubmitSatelliteAudio = channel.unary_unary(
                '/hannah.HannahService/SubmitSatelliteAudio',
                request_serializer=hannah__pb2.SubmitSatelliteAudioRequest.SerializeToString,
                response_deserializer=hannah__pb2.SubmitSatelliteAudioResponse.FromString,
                _registered_method=True)
        self.NotifySatelliteRegistered = channel.unary_unary(
                '/hannah.HannahService/NotifySatelliteRegistered',
                request_serializer=hannah__pb2.SatelliteRegistration.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.NotifySatelliteGone = channel.unary_unary(
                '/hannah.HannahService/NotifySatelliteGone',
                request_serializer=hannah__pb2.SatelliteRegistration.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ProvisionSatellite = channel.unary_unary(
                '/hannah.HannahService/ProvisionSatellite',
                request_serializer=hannah__pb2.ProvisionSatelliteRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.EnrollVoiceprint = channel.unary_unary(
                '/hannah.HannahService/EnrollVoiceprint',
                request_serializer=hannah__pb2.EnrollVoiceprintRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.TimerConnect = channel.stream_stream(
                '/hannah.HannahService/TimerConnect',
                request_serializer=hannah__pb2.TimerMessage.SerializeToString,
                response_deserializer=hannah__pb2.TimerCommand.FromString,
                _registered_method=True)
        self.AgentConnect = channel.stream_stream(
                '/hannah.HannahService/AgentConnect',
                request_serializer=hannah__pb2.AgentMessage.SerializeToString,
                response_deserializer=hannah__pb2.AgentCommand.FromString,
                _registered_method=True)


class HannahServiceServicer:
    """============================================================
    Hannah gRPC Service

    Allows external services (Telegram bot, web UI, etc.) to:
    - query and manage the user registry
    - submit text commands and receive answers
    - trigger TTS announcements on satellites
    - inspect registered satellites
    - query live car state
    - subscribe to a stream of Hannah events (car parked, resident arrived, …)
    - register as a satellite audio proxy (Go gRPC proxy replaces UDP server)
    ============================================================

    """

    def GetUsers(self, request, context):
        """--- User Registry ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlinkAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTrustLevel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSystemMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """--- User-Verwaltung (Admin-UI, #27 Phase 6) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResidents(self, request, context):
        """Residents (Roomies/Guests/Pets) aus dem ioBroker-Adapter-Cache — fürs "Resident verknüpfen"-Dropdown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevices(self, request, context):
        """--- Device Control Menu ---
        Returns all rooms and devices with current state — for building control menus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlDevice(self, request, context):
        """Directly set a device state (bypasses NLU). Trust level check is done by the caller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitText(self, request, context):
        """--- Control ---
        Submit a plain-text command; Hannah processes it through NLU and returns the answer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitVoice(self, request, context):
        """Submit a voice message (OGG/Opus bytes); Hannah does STT → NLU → TTS and returns the result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Announce(self, request, context):
        """Send a TTS announcement to one satellite or all ("all").
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Notify(self, request, context):
        """Send a notification from ioBroker to Hannah. Returns ok=true when queued.
        direct=true: skip LLM reformulation. severity: "alert"|"notify"|"info".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSatellites(self, request, context):
        """List all known satellites (DB + live status merged).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSatelliteRoom(self, request, context):
        """--- Satellites (Admin-UI, #27 Phase 2) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSatelliteDisplayName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSatelliteOwner(self, request, context):
        """Assign a satellite to a Person (User), independent of its room. #31
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRooms(self, request, context):
        """--- Rooms/Groups (Admin-UI, #27 Phase 1) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGroupRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoutines(self, request, context):
        """--- Routines/Triggers (Admin-UI, #27 Phase 4) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRoutine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRoutine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRoutine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTriggers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTrigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTrigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTrigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSettings(self, request, context):
        """--- Settings (Admin-UI, #27 Phase 5) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCarState(self, request, context):
        """--- Car ---
        Returns the current cached car state (available=false if no data received yet).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllCarStates(self, request, context):
        """Returns all tracked car states (one per configured car).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """--- Event stream ---
        Opens a server-side stream; Hannah pushes events as they occur.
        Pass event_types to filter (empty = all events).
        Known event types: "car.parked", "resident.arrived", "resident.departed", "satellite.firmware"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerFirmwareUpdate(self, request, context):
        """--- Firmware Manager ---
        Trigger an immediate OTA update for a satellite (bypasses residents check).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestSatelliteCapture(self, request, context):
        """--- Wakeword Capture ---
        Put a satellite in audio-capture mode for wakeword training data collection.
        While captured: wakeword detection is suspended, speaker is muted, DND is active.
        Hannah relays raw PCM chunks from the satellite to the collector via StreamSatelliteAudio.
        The stream stays open until the collector disconnects; Hannah then auto-releases the satellite.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseSatelliteCapture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSatelliteAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerPlink(self, request, context):
        """Play a plink sound on the satellite, then hold virtual PTT for record_duration seconds.
        Returns after PTT is released — Collector calls this in a loop for guided hey-hannah collection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterProxy(self, request_iterator, context):
        """--- Satellite Proxy (Go gRPC proxy) ---
        Bidirectional keepalive stream. Proxy sends heartbeats; Hannah sends TTS
        audio commands back (for announcements). While this stream is open, Hannah
        disables its own UDP server. If the stream drops, Hannah re-enables UDP.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSatelliteAudio(self, request, context):
        """Submit a complete satellite audio session for processing.
        Hannah runs the full pipeline (STT → NLU → TTS → MQTT status) and returns
        the result so the proxy can play TTS audio back to the satellite.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifySatelliteRegistered(self, request, context):
        """Notify Hannah that a satellite registered or disconnected via the proxy.
        Hannah updates its room registry (hannah/rooms MQTT) immediately.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifySatelliteGone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvisionSatellite(self, request, context):
        """--- Satellite Provisioning ---
        Called by the ioBroker adapter before WebFlash to pre-register a seed + display name + room.
        When the satellite first connects with that seed, Hannah links serial → pre-config and clears the seed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrollVoiceprint(self, request, context):
        """--- Speaker Enrollment ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TimerConnect(self, request_iterator, context):
        """--- Timer Service ---
        Bidirectional stream between the Hannah Timer Service and Hannah Core.
        The Timer Service initiates the connection; if Hannah restarts, the service reconnects.
        Hannah sends timer commands (create, cancel, list); the service fires events when timers expire.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentConnect(self, request_iterator, context):
        """--- ioBroker Agent ---
        Single bidirectional stream between the HannahAgent ioBroker adapter and Hannah Core.
        The adapter pushes state updates (device states, presence, text commands);
        Hannah pushes device-control commands and on-demand state-subscription requests back.
        The adapter initiates the connection; if Hannah restarts, the adapter reconnects.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HannahServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=hannah__pb2.GetUsersRequest.FromString,
                    response_serializer=hannah__pb2.GetUsersResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=hannah__pb2.GetUserRequest.FromString,
                    response_serializer=hannah__pb2.UserResponse.SerializeToString,
            ),
            'LinkAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkAccount,
                    request_deserializer=hannah__pb2.LinkAccountRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'UnlinkAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlinkAccount,
                    request_deserializer=hannah__pb2.UnlinkAccountRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'SetTrustLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTrustLevel,
                    request_deserializer=hannah__pb2.SetTrustLevelRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'SetSystemMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSystemMessages,
                    request_deserializer=hannah__pb2.SetSystemMessagesRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=hannah__pb2.LoginRequest.FromString,
                    response_serializer=hannah__pb2.UserResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=hannah__pb2.CreateUserRequest.FromString,
                    response_serializer=hannah__pb2.CreateUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=hannah__pb2.UpdateUserRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=hannah__pb2.DeleteUserRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'GetResidents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResidents,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.GetResidentsResponse.SerializeToString,
            ),
            'GetDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevices,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.GetDevicesResponse.SerializeToString,
            ),
            'ControlDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlDevice,
                    request_deserializer=hannah__pb2.ControlDeviceRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'SubmitText': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitText,
                    request_deserializer=hannah__pb2.SubmitTextRequest.FromString,
                    response_serializer=hannah__pb2.SubmitTextResponse.SerializeToString,
            ),
            'SubmitVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitVoice,
                    request_deserializer=hannah__pb2.SubmitVoiceRequest.FromString,
                    response_serializer=hannah__pb2.SubmitVoiceResponse.SerializeToString,
            ),
            'Announce': grpc.unary_unary_rpc_method_handler(
                    servicer.Announce,
                    request_deserializer=hannah__pb2.AnnounceRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=hannah__pb2.AgentNotification.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'GetSatellites': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSatellites,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.GetSatellitesResponse.SerializeToString,
            ),
            'SetSatelliteRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSatelliteRoom,
                    request_deserializer=hannah__pb2.SetSatelliteRoomRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'SetSatelliteDisplayName': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSatelliteDisplayName,
                    request_deserializer=hannah__pb2.SetSatelliteDisplayNameRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'SetSatelliteOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSatelliteOwner,
                    request_deserializer=hannah__pb2.SetSatelliteOwnerRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'GetRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRooms,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.GetRoomsResponse.SerializeToString,
            ),
            'GetGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroups,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.GetGroupsResponse.SerializeToString,
            ),
            'CreateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroup,
                    request_deserializer=hannah__pb2.CreateGroupRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGroup,
                    request_deserializer=hannah__pb2.UpdateGroupRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGroup,
                    request_deserializer=hannah__pb2.DeleteGroupRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'SetGroupRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGroupRooms,
                    request_deserializer=hannah__pb2.SetGroupRoomsRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'GetRoutines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoutines,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.GetRoutinesResponse.SerializeToString,
            ),
            'CreateRoutine': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoutine,
                    request_deserializer=hannah__pb2.CreateRoutineRequest.FromString,
                    response_serializer=hannah__pb2.CreateRoutineResponse.SerializeToString,
            ),
            'UpdateRoutine': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRoutine,
                    request_deserializer=hannah__pb2.UpdateRoutineRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteRoutine': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRoutine,
                    request_deserializer=hannah__pb2.DeleteRoutineRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'GetTriggers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTriggers,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.GetTriggersResponse.SerializeToString,
            ),
            'CreateTrigger': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTrigger,
                    request_deserializer=hannah__pb2.CreateTriggerRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateTrigger': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTrigger,
                    request_deserializer=hannah__pb2.UpdateTriggerRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteTrigger': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTrigger,
                    request_deserializer=hannah__pb2.DeleteTriggerRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'GetSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSettings,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.GetSettingsResponse.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=hannah__pb2.UpdateConfigRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'CreateSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSetting,
                    request_deserializer=hannah__pb2.CreateSettingRequest.FromString,
                    response_serializer=hannah__pb2.CreateSettingResponse.SerializeToString,
            ),
            'DeleteSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSetting,
                    request_deserializer=hannah__pb2.DeleteSettingRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'GetCarState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarState,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.CarStateResponse.SerializeToString,
            ),
            'GetAllCarStates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCarStates,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.GetAllCarStatesResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=hannah__pb2.EventFilter.FromString,
                    response_serializer=hannah__pb2.HannahEvent.SerializeToString,
            ),
            'TriggerFirmwareUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerFirmwareUpdate,
                    request_deserializer=hannah__pb2.TriggerFirmwareUpdateRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'RequestSatelliteCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestSatelliteCapture,
                    request_deserializer=hannah__pb2.SatelliteCaptureRequest.FromString,
                    response_serializer=hannah__pb2.SatelliteCaptureResponse.SerializeToString,
            ),
            'ReleaseSatelliteCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseSatelliteCapture,
                    request_deserializer=hannah__pb2.SatelliteCaptureRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'StreamSatelliteAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSatelliteAudio,
                    request_deserializer=hannah__pb2.SatelliteCaptureRequest.FromString,
                    response_serializer=hannah__pb2.SatelliteAudioChunk.SerializeToString,
            ),
            'TriggerPlink': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerPlink,
                    request_deserializer=hannah__pb2.TriggerPlinkRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'RegisterProxy': grpc.stream_stream_rpc_method_handler(
                    servicer.RegisterProxy,
                    request_deserializer=hannah__pb2.ProxyHeartbeat.FromString,
                    response_serializer=hannah__pb2.ProxyCommand.SerializeToString,
            ),
            'SubmitSatelliteAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSatelliteAudio,
                    request_deserializer=hannah__pb2.SubmitSatelliteAudioRequest.FromString,
                    response_serializer=hannah__pb2.SubmitSatelliteAudioResponse.SerializeToString,
            ),
            'NotifySatelliteRegistered': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifySatelliteRegistered,
                    request_deserializer=hannah__pb2.SatelliteRegistration.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'NotifySatelliteGone': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifySatelliteGone,
                    request_deserializer=hannah__pb2.SatelliteRegistration.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'ProvisionSatellite': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvisionSatellite,
                    request_deserializer=hannah__pb2.ProvisionSatelliteRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'EnrollVoiceprint': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollVoiceprint,
                    request_deserializer=hannah__pb2.EnrollVoiceprintRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'TimerConnect': grpc.stream_stream_rpc_method_handler(
                    servicer.TimerConnect,
                    request_deserializer=hannah__pb2.TimerMessage.FromString,
                    response_serializer=hannah__pb2.TimerCommand.SerializeToString,
            ),
            'AgentConnect': grpc.stream_stream_rpc_method_handler(
                    servicer.AgentConnect,
                    request_deserializer=hannah__pb2.AgentMessage.FromString,
                    response_serializer=hannah__pb2.AgentCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hannah.HannahService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hannah.HannahService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HannahService:
    """============================================================
    Hannah gRPC Service

    Allows external services (Telegram bot, web UI, etc.) to:
    - query and manage the user registry
    - submit text commands and receive answers
    - trigger TTS announcements on satellites
    - inspect registered satellites
    - query live car state
    - subscribe to a stream of Hannah events (car parked, resident arrived, …)
    - register as a satellite audio proxy (Go gRPC proxy replaces UDP server)
    ============================================================

    """

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetUsers',
            hannah__pb2.GetUsersRequest.SerializeToString,
            hannah__pb2.GetUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetUser',
            hannah__pb2.GetUserRequest.SerializeToString,
            hannah__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/LinkAccount',
            hannah__pb2.LinkAccountRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlinkAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/UnlinkAccount',
            hannah__pb2.UnlinkAccountRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTrustLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SetTrustLevel',
            hannah__pb2.SetTrustLevelRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSystemMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SetSystemMessages',
            hannah__pb2.SetSystemMessagesRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/Login',
            hannah__pb2.LoginRequest.SerializeToString,
            hannah__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/CreateUser',
            hannah__pb2.CreateUserRequest.SerializeToString,
            hannah__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/UpdateUser',
            hannah__pb2.UpdateUserRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/DeleteUser',
            hannah__pb2.DeleteUserRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResidents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetResidents',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.GetResidentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetDevices',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.GetDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/ControlDevice',
            hannah__pb2.ControlDeviceRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SubmitText',
            hannah__pb2.SubmitTextRequest.SerializeToString,
            hannah__pb2.SubmitTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SubmitVoice',
            hannah__pb2.SubmitVoiceRequest.SerializeToString,
            hannah__pb2.SubmitVoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Announce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/Announce',
            hannah__pb2.AnnounceRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/Notify',
            hannah__pb2.AgentNotification.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSatellites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetSatellites',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.GetSatellitesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSatelliteRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SetSatelliteRoom',
            hannah__pb2.SetSatelliteRoomRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSatelliteDisplayName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SetSatelliteDisplayName',
            hannah__pb2.SetSatelliteDisplayNameRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSatelliteOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SetSatelliteOwner',
            hannah__pb2.SetSatelliteOwnerRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetRooms',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.GetRoomsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetGroups',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.GetGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/CreateGroup',
            hannah__pb2.CreateGroupRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/UpdateGroup',
            hannah__pb2.UpdateGroupRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/DeleteGroup',
            hannah__pb2.DeleteGroupRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGroupRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SetGroupRooms',
            hannah__pb2.SetGroupRoomsRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoutines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetRoutines',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.GetRoutinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRoutine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/CreateRoutine',
            hannah__pb2.CreateRoutineRequest.SerializeToString,
            hannah__pb2.CreateRoutineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRoutine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/UpdateRoutine',
            hannah__pb2.UpdateRoutineRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRoutine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/DeleteRoutine',
            hannah__pb2.DeleteRoutineRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTriggers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetTriggers',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.GetTriggersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/CreateTrigger',
            hannah__pb2.CreateTriggerRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/UpdateTrigger',
            hannah__pb2.UpdateTriggerRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/DeleteTrigger',
            hannah__pb2.DeleteTriggerRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetSettings',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.GetSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/UpdateConfig',
            hannah__pb2.UpdateConfigRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/CreateSetting',
            hannah__pb2.CreateSettingRequest.SerializeToString,
            hannah__pb2.CreateSettingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/DeleteSetting',
            hannah__pb2.DeleteSettingRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCarState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetCarState',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.CarStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllCarStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetAllCarStates',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.GetAllCarStatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hannah.HannahService/SubscribeEvents',
            hannah__pb2.EventFilter.SerializeToString,
            hannah__pb2.HannahEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerFirmwareUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/TriggerFirmwareUpdate',
            hannah__pb2.TriggerFirmwareUpdateRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestSatelliteCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/RequestSatelliteCapture',
            hannah__pb2.SatelliteCaptureRequest.SerializeToString,
            hannah__pb2.SatelliteCaptureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseSatelliteCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/ReleaseSatelliteCapture',
            hannah__pb2.SatelliteCaptureRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSatelliteAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hannah.HannahService/StreamSatelliteAudio',
            hannah__pb2.SatelliteCaptureRequest.SerializeToString,
            hannah__pb2.SatelliteAudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerPlink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/TriggerPlink',
            hannah__pb2.TriggerPlinkRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterProxy(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hannah.HannahService/RegisterProxy',
            hannah__pb2.ProxyHeartbeat.SerializeToString,
            hannah__pb2.ProxyCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitSatelliteAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SubmitSatelliteAudio',
            hannah__pb2.SubmitSatelliteAudioRequest.SerializeToString,
            hannah__pb2.SubmitSatelliteAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifySatelliteRegistered(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/NotifySatelliteRegistered',
            hannah__pb2.SatelliteRegistration.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifySatelliteGone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/NotifySatelliteGone',
            hannah__pb2.SatelliteRegistration.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProvisionSatellite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/ProvisionSatellite',
            hannah__pb2.ProvisionSatelliteRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrollVoiceprint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/EnrollVoiceprint',
            hannah__pb2.EnrollVoiceprintRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TimerConnect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hannah.HannahService/TimerConnect',
            hannah__pb2.TimerMessage.SerializeToString,
            hannah__pb2.TimerCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentConnect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hannah.HannahService/AgentConnect',
            hannah__pb2.AgentMessage.SerializeToString,
            hannah__pb2.AgentCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
