# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: satellite_proxy.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'satellite_proxy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15satellite_proxy.proto\x12\x06hannah\"F\n\x0eProxyHeartbeat\x12\x10\n\x08proxy_id\x18\x01 \x01(\t\x12\x10\n\x08udp_host\x18\x02 \x01(\t\x12\x10\n\x08udp_port\x18\x03 \x01(\x05\"j\n\x0cProxyCommand\x12\x1f\n\x03\x61\x63k\x18\x01 \x01(\x0b\x32\x10.hannah.ProxyAckH\x00\x12.\n\nplay_audio\x18\x02 \x01(\x0b\x32\x18.hannah.PlayAudioCommandH\x00\x42\t\n\x07\x63ommand\"1\n\x08ProxyAck\x12\x14\n\x0cudp_disabled\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"^\n\x10PlayAudioCommand\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\taudio_pcm\x18\x02 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\x0f\n\x07is_last\x18\x04 \x01(\x08\"\x7f\n\x1bSubmitSatelliteAudioRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0c\n\x04room\x18\x02 \x01(\t\x12\x11\n\taudio_pcm\x18\x03 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x04 \x01(\x05\x12\x17\n\x0fspeaker_user_id\x18\x05 \x01(\t\"\x7f\n\x1cSubmitSatelliteAudioResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\x12\x13\n\x0bintent_name\x18\x03 \x01(\t\x12\x11\n\taudio_pcm\x18\x04 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x05 \x01(\x05\"c\n\x15SatelliteRegistration\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x0c\n\x04seed\x18\x05 \x01(\tJ\x04\x08\x02\x10\x03J\x04\x08\x04\x10\x05R\x04roomR\x06serialB=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'satellite_proxy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannah'
  _globals['_PROXYHEARTBEAT']._serialized_start=33
  _globals['_PROXYHEARTBEAT']._serialized_end=103
  _globals['_PROXYCOMMAND']._serialized_start=105
  _globals['_PROXYCOMMAND']._serialized_end=211
  _globals['_PROXYACK']._serialized_start=213
  _globals['_PROXYACK']._serialized_end=262
  _globals['_PLAYAUDIOCOMMAND']._serialized_start=264
  _globals['_PLAYAUDIOCOMMAND']._serialized_end=358
  _globals['_SUBMITSATELLITEAUDIOREQUEST']._serialized_start=360
  _globals['_SUBMITSATELLITEAUDIOREQUEST']._serialized_end=487
  _globals['_SUBMITSATELLITEAUDIORESPONSE']._serialized_start=489
  _globals['_SUBMITSATELLITEAUDIORESPONSE']._serialized_end=616
  _globals['_SATELLITEREGISTRATION']._serialized_start=618
  _globals['_SATELLITEREGISTRATION']._serialized_end=717
# @@protoc_insertion_point(module_scope)
