# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wakeword_capture.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'wakeword_capture.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16wakeword_capture.proto\x12\x06hannah\"A\n\x17SatelliteCaptureRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0bsample_type\x18\x02 \x01(\t\"A\n\x13TriggerPlinkRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x17\n\x0frecord_duration\x18\x02 \x01(\x02\"5\n\x18SatelliteCaptureResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"Q\n\x13SatelliteAudioChunk\x12\x0b\n\x03pcm\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x18\n\x10\x65nd_of_utterance\x18\x03 \x01(\x08\x42=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wakeword_capture_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannah'
  _globals['_SATELLITECAPTUREREQUEST']._serialized_start=34
  _globals['_SATELLITECAPTUREREQUEST']._serialized_end=99
  _globals['_TRIGGERPLINKREQUEST']._serialized_start=101
  _globals['_TRIGGERPLINKREQUEST']._serialized_end=166
  _globals['_SATELLITECAPTURERESPONSE']._serialized_start=168
  _globals['_SATELLITECAPTURERESPONSE']._serialized_end=221
  _globals['_SATELLITEAUDIOCHUNK']._serialized_start=223
  _globals['_SATELLITEAUDIOCHUNK']._serialized_end=304
# @@protoc_insertion_point(module_scope)
